### ISSUE TITLE
Notebook of 8.7 part 2 is contains error

### ISSUE THREAD

**Issue by GegznaV** [Lightning-AI/dl-fundamentals#102]
The committed version of [`part2_distilbert-finetune-last-layers.ipynb`](https://github.com/Lightning-AI/dl-fundamentals/blob/main/unit08-large-language-models/8.7-distilbert-finetuning/part2_distilbert-finetune-last-layers.ipynb) contains error:

![image](https://github.com/Lightning-AI/dl-fundamentals/assets/12725868/062d06e4-afe0-44be-b3cd-61975e9fdb6b)

I believe the path should be something else than "csv".

**Comment by rasbt** [comment]
I tend to agree, but it's bizarre. Tested it with "csv" and it works fine even though there is no "csv" folder:

<img width="807" alt="Screenshot 2024-02-28 at 9 29 16 AM" src="https://github.com/Lightning-AI/dl-fundamentals/assets/5618407/e1057891-9919-498e-b23e-4d87b92be46e">


But then changing it to something else doesn't work:

<img width="576" alt="Screenshot 2024-02-28 at 9 32 25 AM" src="https://github.com/Lightning-AI/dl-fundamentals/assets/5618407/d79fcb86-e7e1-433d-962b-768e94f42223">


maybe the `datatsets.load_dataset` function is doing something weird here ... I.e., I think that it becomes more of a "format" designator if `data_files` is provided: https://github.com/huggingface/datasets/blob/cf1aaa32eddd73076cf6600125661df4a32cb20a/src/datasets/load.py#L2483C19-L2483C76

You can see it here when changing to "json":

<img width="597" alt="Screenshot 2024-02-28 at 9 36 23 AM" src="https://github.com/Lightning-AI/dl-fundamentals/assets/5618407/5b818a54-d650-4ebc-af5e-a966993cf01e">

Kind of a weird design choice in `load_dataset` to override `"path"` this way imho. Very confusing.

**Comment by GegznaV** [comment]
Will the notebook which does not show the error in the block will be uploaded to GitHub? As my screenshot is from GitHub: the error occurred on the machine of the person who uploaded the notebool last time. 

For me `"csv"` also works if datasets are in the working directory, but it feels _weird_ to download a notebook that contains an error in a cell.

**Comment by GegznaV** [comment]
I downloaded data to a different directory, so at first, I thought that the issue was the `"csv"` value.

**Comment by rasbt** [comment]
> For me "csv" also works if datasets are in the working directory, but it feels weird to download a notebook that contains an error in a cell.

Ohh, I had a different local file and totally missed that. Should be fixed now. Thanks again!
