### ISSUE TITLE
[ui] Issues navigating through video sections 

### ISSUE THREAD

**Issue by piskunovim** [Lightning-AI/dl-fundamentals#30]
Hello, thanks for your course. I appreciate your work. Unfortunately, I ran into **two issues** navigating the course.

##  "Next Video" doesn't work.

When you are on the last video of a Unit subsection, there is a "Next Video" button, which is "slick-disabled" in the button class, but in fact, there is no difference from the "Previous Video" button in behavior. It feels like the button isn't working.

![image](https://user-images.githubusercontent.com/5876617/229351058-6c687c88-0360-438a-8111-570d0bd81bc2.png)
![image](https://user-images.githubusercontent.com/5876617/229351777-84068b2b-9cff-4e81-a2fb-9eaa7d16a469.png)

**Expected result:**
The button either leads to the next video or is missing because the video section is over.

**Actual result:**
The button is present but doesn't indicate about it can no longer be used.

## Quiz number 2 without video 2.

It was kind of a surprise to see two quizzes in the first video. It triggered me to click "Next Video" so I determined that each subsection is represented with multiple videos like that:

![image](https://user-images.githubusercontent.com/5876617/229352037-601dfc4c-3963-49c8-9b9e-5861f914238c.png)

**Expected result:**
Clean information about nesting within subsections.
![image](https://user-images.githubusercontent.com/5876617/229352538-22a80041-c592-4e1e-a1f2-e67e4c743cc9.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/5876617/229352066-c120f4bd-6569-4b0b-9132-f9e48d4d124b.png)

**Comment by rasbt** [comment]
Thanks a lot for the suggestion and recommending the alternative layout. I agree that it's easy to overlook the multiple videos, and it would be nice to update this. I will forward it to our web dev. Many thanks!!

**Comment by rasbt** [comment]
Thanks again for bringing up these issues. One fix in the meantime is to show the "next video" at the bottom in case someone missed it. 
<img width="810" alt="Screenshot 2023-06-16 at 4 41 16 PM" src="https://github.com/Lightning-AI/dl-fundamentals/assets/5618407/92b8af31-ee3d-4f91-90e9-0cb6b165a27a">
