### ISSUE TITLE
[ui] Mathematical equations in the exercises show their LaTeX formats.

### ISSUE THREAD

**Issue by ARKA1112** [Lightning-AI/dl-fundamentals#34]
Hi, I am currently pursuing this course and found it really great. The exercises at the end of each units/sub-units is a great addition in order to check the understanding. However I found out that the equations in the exercises are still in their LaTeX format.

Here's an example:
![Screenshot from 2023-04-06 21-10-10](https://user-images.githubusercontent.com/24940818/230429206-070b0166-1f01-41f8-a67d-c4b3ef140b7b.png)

<b>The expected notation should be</b>  $x_{3}^{[5]}$

**Comment by rasbt** [comment]
Sorry, I missed this somehow! Will try to get this fixed today. Thanks a lot for the note!

**Comment by rasbt** [comment]
Forgot to update, but yeah, it should all be fixed now! Thanks again for raising this!
