### ISSUE TITLE
Minor typo in Pandas URL in section 1.6

### ISSUE THREAD

**Issue by the-lazy-learner** [Lightning-AI/dl-fundamentals#42]
On section 1.6 about [implementing a perceptron]("https://lightning.ai/pages/courses/deep-learning-fundamentals/unit-1/1-6-implementing-a-perceptron-in-python-parts-1-3/") the URL for Pandas documentation has a typo. Instead of being, `https://pandas.pydata.or` it should have linked to `https://pandas.pydata.org/`. This is a very minor typo. And thank you for the great job with the course.

**Comment by rasbt** [comment]
thanks will get that fixed!

**Comment by rasbt** [comment]
Fixed!
