### ISSUE TITLE
Accuracy is always 0

### ISSUE THREAD

**Issue by nicoforteza** [Lightning-AI/dl-fundamentals#44]
Hi, 

Im using the following custom data to reproduce this [notebook.](https://github.com/Lightning-AI/dl-fundamentals/blob/main/unit08-large-language-models/8.7-distilbert-finetuning/part2_distilbert-finetune-last-layers.ipynb):

 - [test.csv](https://github.com/Lightning-AI/dl-fundamentals/files/11406875/test.csv)
 - [train.csv](https://github.com/Lightning-AI/dl-fundamentals/files/11406877/train.csv)
 - [val.csv](https://github.com/Lightning-AI/dl-fundamentals/files/11406879/val.csv)

It is a multiclass label. However, I'm getting 0 loss and 0 accuracy. Any suggestion? 
Thanks!

**Comment by rasbt** [comment]
I would double check the labels, are they 0, 1, 2, etc.?

The other things is it looks line the text is non-English. So you maybe have to switch to a multilingual model like "distilbert-base-multilingual-cased"

**Comment by rasbt** [comment]
Were you able to address the issue? If not, let me know if you'd like some additional pointers
