### ISSUE TITLE
[ui] Reporting Quiz 4.1 (PART 4) UI Issue

### ISSUE THREAD

**Issue by jihoonkim2100** [Lightning-AI/dl-fundamentals#56]
Thank you for the aswesome courses. I wanted to express my appreciation for the engaging quizzes and exercises provided for each unit. They have been instrumental in keeping me motivated and actively learning throughout the course.

However, while working on Quiz 4.1, I came across a UI error that I would like to bring to your attention. Here are the specifies of the error:

### `Quiz 4.1, Dealing with More than Two Classes: Softmax Regression (PART 4)` quiz option buttons don't work

When attempting to click my anwers for [Quiz 4.1 (PART 4)](https://lightning.ai/pages/courses/deep-learning-fundamentals/training-multilayer-neural-networks-overview/logistic-regression-for-multiple-classes-part-1-5/), I noticed that the "Radio button" options are unresponsive due to typo coding in UI. Therefore, clicking on the button does not trigger any action. I have attached a screenshot of the unresponsive "Radio buttion" option page for your reference.

![ui _quiz_error](https://github.com/Lightning-AI/dl-fundamentals/assets/39021807/9d574e2d-1664-4fce-b4ce-c62c574c64ca)

**Expected result:**
- Ability to click on audio buttons
- Concise text answer options for questions

**Actual result:**
- The button does not trigger any action
- Typo text included in text answer options e.g. `1,-0,-0,-0,-0
-1" name="question-1" value="
1,-0,-0,-0,-0
-1"> 1,-0,-0,-0,-0
-1">
1, 0, 0, 0, 0`

P.S. During the process of identifying and investigating a UI issue, I unintentionally discovered a method to easily bypass the correct answers in a quiz, enabling me to easily find out the answers. It may be necessary to implement measures to prevent such an approach.

**Comment by rasbt** [comment]
Thanks for the feedback! I appreciate it! The good news is that it should be fixed now 😊
