### ISSUE TITLE
cli = LightningCLI( TypeError: __init__() got an unexpected keyword argument 'save_config_overwrite'

### ISSUE THREAD

**Issue by RyderZ-Neo** [Lightning-AI/dl-fundamentals#63]
Hello Rasbt,
Thank you for your awesome course. 
 I ran into above problem while running mlp_cli.py  for section 6.5 . Is that parameter no longer available in lightning 2.0.2 ? 

https://github.com/Lightning-AI/dl-fundamentals/blob/68bc6ca7716c315301723d41a66cfc34aa5d20dc/unit06-dl-tips/6.5-hparam-opt/6.5-part2-cli-simple/mlp_cli.py#LL18C36-L18C36

<img width="1036" alt="image" src="https://github.com/Lightning-AI/dl-fundamentals/assets/41388975/316b9fdb-0b41-4339-896e-046d0bebbea6">

**Comment by meghavarshini** [comment]
I got the same error message as well. Based on the [LightningCLI documentation on the update 2.0](https://lightning.ai/docs/pytorch/stable/upgrade/from_1_9.html), we need to "pass this option and via dictionary of save_config_kwargs parameter".

So, the proposed change is `save_config_kwargs={"overwrite": None}`

None: This may generate a warning about the absence of the jsonargparse library. I resolved it by following the warning's advice and using `pip install -U 'jsonargparse[signatures]>=4.17.0'`
