### ISSUE TITLE
Unrendered equations in the quizzes

### ISSUE THREAD

**Issue by Sai-Nandan-Desetti** [Lightning-AI/dl-fundamentals#70]
### Discussed in https://github.com/Lightning-AI/dl-fundamentals/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **Sai-Nandan-Desetti** June 30, 2023</sup>
The mathematical notation in Quiz: 1.4 The First Machine Learning Classifier. Part 3 isn't rendered. (We get the idea of what it means, nevertheless.)</div>

**Comment by Sai-Nandan-Desetti** [comment]
Sorry! This issue is already addressed [here](https://github.com/Lightning-AI/dl-fundamentals/issues/34). I simply had to refresh the page. (I've no idea why it showed an unrendered equation initially though.)

**Comment by Sai-Nandan-Desetti** [comment]
Now again I see this which doesn't display in its rendered form even upon refreshing!
![Unrendered equation](https://github.com/Lightning-AI/dl-fundamentals/assets/80631906/46932c24-fba8-4dff-b148-df6764683e82)

**Comment by rasbt** [comment]
Sorry about that, not sure why this problem happened again. But thanks for the note. Should be fixed again now!
<img width="997" alt="Screenshot 2023-07-06 at 12 46 06 PM" src="https://github.com/Lightning-AI/dl-fundamentals/assets/5618407/4e938f45-a1b6-4044-8e60-e0d4f72c6d12">
