### ISSUE TITLE
Watch video 2 button for units with one video (unit 1.3, 1.5, 2.1 etc)

### ISSUE THREAD

**Issue by ssuzana** [Lightning-AI/dl-fundamentals#75]
I noticed that some sections have only one video, but there is still a button labeled "Watch video 2" on those pages, even though there is no video 2.
See units: 1.3, 1.5, 2.1, 2.3, 2.5, 2.6, 2.7, 3.2, 3.4, 4.6, 5.1, 5.8, 6.4, 10.3, 10.4.

Here's a picture for unit 1.3:
<img width="1123" alt="Screenshot 2023-07-14 at 4 46 52 PM" src="https://github.com/Lightning-AI/dl-fundamentals/assets/74042651/782e3fba-0b3e-4915-a6c9-8b8ff4151048">

**Comment by rasbt** [comment]
Good point! Thanks for bringing this up! I'll mention this to our web dev who can hopefully address this!

**Comment by rasbt** [comment]
Thanks again for mentioning this! Happy to share that it should be fixed now!
