### ISSUE TITLE
Wrong pdf link in 8.3 Introduction to Recurrent Neural Networks part 2

### ISSUE THREAD

**Issue by byvuong** [Lightning-AI/dl-fundamentals#89]
Hi,

The pdf link is not correct for [Part 2: The Different Sequence Modeling Tasks](https://drive.google.com/file/d/1Xn3iGXrkzcC2aOF5o2_D82ra8J73gCJV/view?usp=share_link)

Thank you

**Comment by byvuong** [comment]
Same for [Part 2: Why Do We Need Attention?](https://drive.google.com/file/d/1_vgAjtAUwB3IU2zVsuY4spAOOxHsZ-9b/view?usp=share_link) in Unit 8.4 From RNNs to the Transformer Architecture. Ty!

**Comment by rasbt** [comment]
Thanks for the note, I will fix that on the website Monday. In the meantime, here are the links for your convenience:

- [8.3 part 2](https://drive.google.com/file/d/1iS0QP6gxqkxM_cCiVGjGRslRpJJZ2bW0/view?usp=share_link)
- [8.4 part 2](https://drive.google.com/file/d/1IPX_kc5AcD5S_O-GxhnY1evYqz2av1qx/view?usp=share_link)

**Comment by rasbt** [comment]
Should be fixed on the website now, too. Thanks again for mentioning the issue. Please let me know in case you stumble upon other things as well.
